/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import Connect.ConnectDB1;
import dao.NhanVienHCDAO;
import dao.PhongBanDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import entity.NhanVien;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.io.ObjectOutput;
import javax.swing.JComboBox;
import entity.PhongBan;
import javax.swing.DefaultComboBoxModel;
import java.sql.Date;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import dao.ChamCongNVDAO;
/**
 *
 * @author ADMIN
 */
public class ChamCongNV extends javax.swing.JPanel {
    ChamCongNVDAO chamCongdao;
    DefaultTableModel modelNV;
    /**
     * Creates new form ChamCongNV
     */
    public ChamCongNV() {
        initComponents();
        try {
          ConnectDB1.getInstance().connect();
        } catch (Exception e) {
            e.printStackTrace();
        }
        chamCongdao = new ChamCongNVDAO();
        modelNV = (DefaultTableModel) tblNV.getModel();
        readTableNV();
    }

    public void readTableNV(){
        modelNV.setRowCount(0);
        List<NhanVien> lst = chamCongdao.getNVChamCong();
        //SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        for (NhanVien nv : lst) {
            Object[] row = {nv.getMaNV(),nv.getHoTen(),nv.getSdt(),nv.getMaPB().getMaPB()};
            modelNV.addRow(row);
        }
        System.out.println(modelNV.getRowCount());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNV = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        myButton4 = new custom_button.MyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCong = new javax.swing.JTable();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CHẤM CÔNG NHÂN VIÊN");
        add(jLabel1);
        jLabel1.setBounds(460, 10, 307, 45);

        tblNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ Tên", "Phòng ban", "SÐT"
            }
        ));
        tblNV.setPreferredSize(new java.awt.Dimension(300, 400));
        tblNV.setRowHeight(30);
        jScrollPane1.setViewportView(tblNV);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 570, 220);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Ngày chấm");
        add(jLabel2);
        jLabel2.setBounds(900, 80, 80, 30);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setText("NV01");
        jTextField1.setEnabled(false);
        add(jTextField1);
        jTextField1.setBounds(680, 80, 140, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Họ Tên:");
        add(jLabel3);
        jLabel3.setBounds(620, 140, 60, 30);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField2.setText("Nguyễn Anh Tuấn");
        jTextField2.setEnabled(false);
        add(jTextField2);
        jTextField2.setBounds(680, 140, 200, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("SÐT:");
        add(jLabel4);
        jLabel4.setBounds(620, 190, 60, 30);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField3.setText("0392887340");
        jTextField3.setEnabled(false);
        add(jTextField3);
        jTextField3.setBounds(680, 190, 200, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("PB:");
        add(jLabel5);
        jLabel5.setBounds(620, 240, 40, 30);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField4.setText("HC");
        jTextField4.setEnabled(false);
        add(jTextField4);
        jTextField4.setBounds(680, 240, 60, 30);
        add(jDateChooser2);
        jDateChooser2.setBounds(990, 80, 138, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("Mã NV:");
        add(jLabel6);
        jLabel6.setBounds(620, 80, 60, 30);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setText("Có mặt/Vắng mặt");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1);
        jCheckBox1.setBounds(1000, 140, 150, 30);

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox2.setText("Có Phép");
        add(jCheckBox2);
        jCheckBox2.setBounds(1000, 180, 110, 30);

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox3.setText("Tăng ca");
        add(jCheckBox3);
        jCheckBox3.setBounds(1000, 220, 85, 24);

        myButton4.setText("Chấm công");
        myButton4.setBorderColor(new java.awt.Color(102, 102, 102));
        myButton4.setColorhover(new java.awt.Color(0, 255, 255));
        myButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myButton4.setRadius(30);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });
        add(myButton4);
        myButton4.setBounds(820, 300, 120, 50);

        tblCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Công", "Mã NV", "Họ Tên", "Phòng Ban", "Ngày Chấm", "Có mặt", "Nghỉ phép", "Tăng ca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCong.setRowHeight(30);
        jScrollPane2.setViewportView(tblCong);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 382, 1200, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private custom_button.MyButton myButton4;
    private javax.swing.JTable tblCong;
    private javax.swing.JTable tblNV;
    // End of variables declaration//GEN-END:variables
}
