/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import connect.ConnectDB1;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.awt.*;
import dao.SanPhamDAO;
import dao.CongNhanDAO;
import dao.CongDoanSPDAO;
import dao.PhanCongDAO;
import dao.CaLamViecDAO;
import dao.ChamCongCNDAO;
import dao.CongDoanSPDAO;
import entity.BangCongCN;
import entity.CongDoan;
import entity.CongNhan;
import entity.PhanCong;
import entity.CaLamViec;

import entity.SanPham;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.sql.Date;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tuan Kiet Admin
 */
public class ChamCongCN extends javax.swing.JPanel {

    private SanPhamDAO spdao;
    private CongDoanSPDAO cddao;
    private PhanCongDAO pcdao;
    private CaLamViecDAO cadao;
    private ChamCongCNDAO ccdao;
    DefaultTableModel modelPC;
    DefaultTableModel modelCC;

    /**
     * Creates new form ChamCongCN
     */
    public ChamCongCN() {
        initComponents();
        ConnectDB1.getInstance().connect();
        modelPC = (DefaultTableModel) tblPhanCong.getModel();
        spdao = new SanPhamDAO();
        pcdao = new PhanCongDAO();
        cadao = new CaLamViecDAO();
        ccdao = new ChamCongCNDAO();
        //loadComboBoxMaCĐ();
//        loadComboBoxTenSP();
//        loadComboBoxTenCĐ();
        modelCC = (DefaultTableModel) tblChamCong.getModel();
//       loadComboBoxCaLamViec();
        loadComboBoxCaLamViec();
    }

    public void getDSPhanCong() {
        modelPC.setRowCount(0);
        List<PhanCong> list = pcdao.getPhanCong();
        modelPC.setRowCount(0);
        for (PhanCong pc : list) {

            Object[] row = {pc.getMaCN().getMaCN(), pc.getTenCN().getTenCN(), pc.getMaCD().getMaCD(), pc.getTenCD().getTenCD(), pc.getMaSP().getMaSP(), pc.getTenSP().getTenSP()};
            modelPC.addRow(row);
        }
    }

    public void clickTable() {
        int row = tblPhanCong.getSelectedRow();
        txtMaCN.setText(modelPC.getValueAt(row, 0).toString());

        txtTenCN.setText(modelPC.getValueAt(row, 1).toString());
        txtMaCĐ.setText(modelPC.getValueAt(row, 2).toString());
         txtTenCĐ.setText(modelPC.getValueAt(row, 3).toString());

        String macđ = modelPC.getValueAt(row, 2).toString();
        String macn = modelPC.getValueAt(row, 0).toString();
        int sl = ccdao.findSL(macđ, macn);
        lblsoluong.setText("" + sl);

    }

    public void loadComboBoxTenCĐ() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaCa.getModel();
        model.removeAllElements();

        List<CaLamViec> lst = cadao.getAllCaLamViec();

        for (CaLamViec ca : lst) {
            model.addElement(ca.getMaCa());

        }
        cboMaCa.setSelectedIndex(0);
    }

    public void loadComboBoxCaLamViec() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaCa.getModel();
        model.removeAllElements();

        List<CaLamViec> lst = cadao.getAllCaLamViec();
        for (CaLamViec ca : lst) {
            model.addElement(ca.getMaCa());
        }
        cboMaCa.setSelectedIndex(0);
        if (cboMaCa.getSelectedItem().toString().equals("CA01")) {
            txtGioLam.setText("7h-11h");
            txtTenCa.setText("Sáng");
        }

    }

    public void loadgiotheoten() {
        String ten = cboMaCa.getSelectedItem().toString();
        String giolam = ccdao.layGioLamtheoca(ten);
        txtGioLam.setText(giolam);
    }
    private int soluongconlai(){
        return Integer.parseInt(lblsoluong.getText())- Integer.parseInt(txtSL.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhanCong = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTenCĐ = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dateNgayCham = new com.toedter.calendar.JDateChooser();
        txtGioLam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        txtMaCN = new javax.swing.JTextField();
        txtTenCĐ = new javax.swing.JTextField();
        txtMaCĐ = new javax.swing.JTextField();
        lblsoluong = new javax.swing.JLabel();
        cboMaCa = new javax.swing.JComboBox<>();
        txtTenCa = new javax.swing.JTextField();
        lblmaSP = new javax.swing.JLabel();
        txtTenCN = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setText("CHẤM CÔNG CÔNG NHÂN");

        tblPhanCong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblPhanCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã CN", "Tên CN", "Mã Công Đoạn", "Tên Công Đoạn", "Mã SP", "Tên SP"
            }
        ));
        tblPhanCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhanCongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhanCong);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã CN");

        lblTenCĐ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTenCĐ.setText("Tên Công Đoạn:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mã Công Đoạn:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Ngày Chấm:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Ca Làm:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Giời Làm:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Mã ca:");

        txtGioLam.setEnabled(false);
        txtGioLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioLamActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Lấy Công Nhân Chấm Công");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel11.setText("Còn Lại:");

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Chấm Công");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Xóa");

        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã CN", "Tên CN", "Mã CĐ", "Tên CĐ", "Mã Ca", "Tên Ca", "Số SP Làm Được", "Trạng Thái", "Ngày Chấm"
            }
        ));
        jScrollPane2.setViewportView(tblChamCong);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Số Lượng Làm Được:");

        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });

        txtMaCN.setEnabled(false);

        txtTenCĐ.setEnabled(false);

        txtMaCĐ.setEnabled(false);

        cboMaCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaCaActionPerformed(evt);
            }
        });
        cboMaCa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cboMaCaKeyTyped(evt);
            }
        });

        txtTenCa.setEnabled(false);

        lblmaSP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblmaSP.setText("Tên CN:");

        txtTenCN.setEnabled(false);
        txtTenCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenCNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(60, 60, 60)
                                                        .addComponent(lblsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTenCĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17)
                                                .addComponent(txtTenCĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lblmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(txtTenCN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)
                                                .addComponent(txtMaCĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(80, 80, 80))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateNgayCham, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMaCa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGioLam, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenCa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel6)
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel10)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel8)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dateNgayCham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(cboMaCa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(txtGioLam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(txtTenCa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTenCN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblTenCĐ))
                                    .addComponent(txtTenCĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtMaCĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGioLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioLamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        getDSPhanCong();
    }//GEN-LAST:event_jButton1MouseClicked

    private void tblPhanCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhanCongMouseClicked
        // TODO add your handling code here:
        clickTable();
    }//GEN-LAST:event_tblPhanCongMouseClicked

    private void cboMaCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaCaActionPerformed
        layGiolamTheoMaCa();
        layTencaTheoMaCa();        // TODO add your handling code here

    }//GEN-LAST:event_cboMaCaActionPerformed
    public void layGiolamTheoMaCa() {
        String maCa = cboMaCa.getSelectedItem().toString();

        String ca = ccdao.layGioLamtheoca(maCa);
        txtGioLam.setText(ca);

    }

    public void layTencaTheoMaCa() {
        String maCa = cboMaCa.getSelectedItem().toString();

        String ca = ccdao.layTenCatheoMaca(maCa);
        txtTenCa.setText(ca);

    }
    private void cboMaCaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMaCaKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_cboMaCaKeyTyped

    private void txtTenCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenCNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ChamCong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
          
    }//GEN-LAST:event_jButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboMaCa;
    private com.toedter.calendar.JDateChooser dateNgayCham;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTenCĐ;
    private javax.swing.JLabel lblmaSP;
    private javax.swing.JLabel lblsoluong;
    private javax.swing.JTable tblChamCong;
    private javax.swing.JTable tblPhanCong;
    private javax.swing.JTextField txtGioLam;
    private javax.swing.JTextField txtMaCN;
    private javax.swing.JTextField txtMaCĐ;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTenCN;
    private javax.swing.JTextField txtTenCa;
    private javax.swing.JTextField txtTenCĐ;
    // End of variables declaration//GEN-END:variables

    public void xoaTrang() {
        txtMaCN.setText("");
        txtTenCN.setText("");
         txtMaCĐ.setText("");
        txtTenCĐ.setText("");
         txtGioLam.setText("");
        txtTenCa.setText("");
        txtSL.setText("");
        lblsoluong.setText("");
        dateNgayCham.setDate(null);
        cboMaCa.setSelectedIndex(0);

    }

    public void ChamCong() {
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String macn = txtMaCN.getText().trim();
        String tencn = txtTenCN.getText().trim();
        String maCD = txtMaCĐ.getText().trim();
         String tenSD = txtTenCĐ.getText().trim();
        String sl = txtSL.getText().trim();
        String gl = txtGioLam.getText().trim();
        String tenca = txtTenCa.getText().trim();
        Date ns = Date.valueOf(df.format(dateNgayCham.getDate()));
        String maca = cboMaCa.getSelectedItem().toString();
        
        CaLamViec clv = new CaLamViec(maca, tenca, gl);
        CongNhan cn = new CongNhan(macn, tencn);
        CongDoan cd = new CongDoan(maCD, tenSD);
        BangCongCN bc = new BangCongCN(clv, clv, cn, cn, cd, cd, Integer.parseInt(sl), ns, cd);
        System.out.println(ccdao.craeateChamCongAndUpdateCD(bc, soluongconlai()));
        if(ccdao.craeateChamCongAndUpdateCD(bc, soluongconlai())){
            Object[] row = {bc.getMaCN().getMaCN(), bc.getTenCN().getTenCN(), bc.getMaCD().getMaCD(), bc.getTenCD().getTenCD(), bc.getMaCa().getMaCa(),
                            bc.getTenCa().getTenCa(), bc.getSoLuongLamDc(), bc.getTrangThai().kiemTraCongDoan(), df.format(bc.getNgayCham())};
            modelCC.addRow(row);
        }
        if(ccdao.updateCongDoan(bc, soluongconlai())){
            JOptionPane.showMessageDialog(this, "cap nhật thành công");
        }
        else{
            JOptionPane.showMessageDialog(this, "cập nhật thất bại");
        }
        
    }
}
