/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import Connect.ConnectDB1;
import javax.swing.table.DefaultTableModel;
import dao.SanPhamDAO;
import dao.CongNhanDAO;
import dao.CongDoanSPDAO;
import dao.PhanCongDAO;
import dao.CaLamViecDAO;
import dao.ChamCongCNDAO;
import dao.CongDoanSPDAO;
import entity.CongDoan;
import entity.CongNhan;
import entity.PhanCong;
import entity.CaLamViec;

import entity.SanPham;

import java.util.ArrayList;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tuan Kiet Admin
 */
public class ChamCongCN extends javax.swing.JPanel {
    private SanPhamDAO spdao;
    private CongDoanSPDAO cddao;
    private PhanCongDAO pcdao;
    private CaLamViecDAO cadao;
    private ChamCongCNDAO ccdao;
    DefaultTableModel modelPC;
     DefaultTableModel modelCC;

   

    /**
     * Creates new form ChamCongCN
     */
    public ChamCongCN() {
         initComponents();
        ConnectDB1.getInstance().connect();
        modelPC = (DefaultTableModel) tblPhanCong.getModel();
        spdao = new SanPhamDAO();
        pcdao = new PhanCongDAO();
        cadao = new CaLamViecDAO();
        ccdao = new ChamCongCNDAO();
        //loadComboBoxMaCĐ();
//        loadComboBoxTenSP();
//        loadComboBoxTenCĐ();
      
//       loadComboBoxCaLamViec();
        loadComboBoxCaLamViec();

      


    }

//   
//    public void loadComboBoxTenSP() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenSP.getModel();
//        model.removeAllElements();
//
//        List<PhanCong> lst = pcdao.getPhanCong();
//        for (PhanCong pc : lst) {
//            model.addElement(pc.getTenSP().getTenSP());
//        }
//        cboTenSP.setSelectedIndex(0);
//    }
//
//    public void loadComboBoxMaCĐ() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaCĐ.getModel();
//        model.removeAllElements();
//
//        List<PhanCong> lst = pcdao.getPhanCong();
//        for (PhanCong pc : lst) {
//            model.addElement(pc.getMaCD().getMaCD());
//        }
//        cboMaCĐ.setSelectedIndex(0);
//    }
    public void getDSPhanCong(){
                modelPC.setRowCount(0);
        List<PhanCong> list = pcdao.getPhanCong();
        modelPC.setRowCount(0);
        for (PhanCong pc : list) {
            
            Object[] row = {pc.getMaCN().getMaCN(),pc.getTenCN().getTenCN(),pc.getMaCD().getMaCD(),   pc.getTenCD().getTenCD(),pc.getMaSP().getMaSP(), pc.getTenSP().getTenSP()};
            modelPC.addRow(row);
        }
    }
    public void clickTable(){ 
        int row = tblPhanCong.getSelectedRow();
        txtTenSP.setText(modelPC.getValueAt(row, 5).toString());
        
        txtTenCĐ.setText(modelPC.getValueAt(row, 1).toString());
//        try {
//            DateNgaySinh.setDate(new SimpleDateFormat("dd-MM-yyyy").parse((String)modelCN.getValueAt(row, 6)));
//        } catch (ParseException ex) {
//            Logger.getLogger(pnCapNhatNV.class.getName()).log(Level.SEVERE, null, ex);
//        }
        txtMaCĐ.setText(modelPC.getValueAt(row, 2).toString());
//        txtDiachi.setText(modelPC.getValueAt(row, 4).toString());
//        txtSđt.setText(modelCN.getValueAt(row, 3).toString());
//        cboPB.setSelectedItem(modelCN.getValueAt(row, 1).toString());
//        txtMa.setEditable(false);
        
    }
//    public void loadComboBoxTenCĐ() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenCđ.getModel();
//        model.removeAllElements();
//
//        List<PhanCong> lst = pcdao.getPhanCong();
//
//        for (PhanCong pc : lst) {
//            model.addElement(pc.getTenCD().getTenCD());
//
//        }
//        cboTenCđ.setSelectedIndex(0);
//    }

    public void loadComboBoxCaLamViec() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboCa.getModel();
        model.removeAllElements();

        List<CaLamViec> lst = cadao.getAllCaLamViec();
        for (CaLamViec ca : lst) {
            model.addElement(ca.getTenCa());
        }
        cboCa.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhanCong = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cboCa = new javax.swing.JComboBox<>();
        txtGioLam = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtTenCĐ = new javax.swing.JTextField();
        txtMaCĐ = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setText("CHẤM CÔNG CÔNG NHÂN");
        add(jLabel1);
        jLabel1.setBounds(560, 14, 282, 26);

        tblPhanCong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblPhanCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã CN", "Tên CN", "Mã Công Đoạn", "Tên Công Đoạn", "Mã SP", "Tên SP"
            }
        ));
        tblPhanCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhanCongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhanCong);

        add(jScrollPane1);
        jScrollPane1.setBounds(6, 58, 675, 240);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Tên Sản Phẩm:");
        add(jLabel3);
        jLabel3.setBounds(780, 70, 86, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Tên Công Đoạn:");
        add(jLabel4);
        jLabel4.setBounds(772, 113, 93, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mã Công Đoạn:");
        add(jLabel5);
        jLabel5.setBounds(776, 161, 89, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Ngày Chấm:");
        add(jLabel6);
        jLabel6.setBounds(1088, 58, 70, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Ca Làm:");
        add(jLabel7);
        jLabel7.setBounds(1111, 119, 47, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Giời Làm:");
        add(jLabel8);
        jLabel8.setBounds(1110, 210, 55, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Mã ca:");
        add(jLabel10);
        jLabel10.setBounds(1120, 250, 38, 17);
        add(jDateChooser1);
        jDateChooser1.setBounds(1176, 58, 204, 30);

        cboCa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCaActionPerformed(evt);
            }
        });
        add(cboCa);
        cboCa.setBounds(1180, 110, 204, 30);

        txtGioLam.setEnabled(false);
        txtGioLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioLamActionPerformed(evt);
            }
        });
        add(txtGioLam);
        txtGioLam.setBounds(1180, 200, 204, 30);

        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3);
        jTextField3.setBounds(1180, 240, 204, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Lấy Công Nhân Chấm Công");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(731, 262, 236, 42);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel11.setText("Số lượng công đoạn còn lại:");
        add(jLabel11);
        jLabel11.setBounds(892, 316, 190, 21);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Chấm Công");
        add(jButton2);
        jButton2.setBounds(796, 349, 116, 36);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Xóa");
        add(jButton3);
        jButton3.setBounds(1057, 349, 116, 36);

        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Chấm Công", "Tên CN", "Mã Công Đoạn", "Tên Công Đoạn", "Ngày Chấm Công", "Mã Ca", "Trạng thái", "Số Lượng Làm "
            }
        ));
        jScrollPane2.setViewportView(tblChamCong);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 397, 1446, 360);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Số Lượng Làm Được:");
        add(jLabel2);
        jLabel2.setBounds(741, 209, 124, 17);

        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });
        add(txtSL);
        txtSL.setBounds(883, 202, 96, 30);

        txtTenSP.setEnabled(false);
        add(txtTenSP);
        txtTenSP.setBounds(880, 60, 180, 30);

        txtTenCĐ.setEnabled(false);
        add(txtTenCĐ);
        txtTenCĐ.setBounds(880, 110, 180, 30);

        txtMaCĐ.setEnabled(false);
        add(txtMaCĐ);
        txtMaCĐ.setBounds(880, 152, 180, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGioLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioLamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void cboCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCaActionPerformed
        // TODO add your handling code here:
 //       layGioLamThepTenca();
    }//GEN-LAST:event_cboCaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
          getDSPhanCong();
    }//GEN-LAST:event_jButton1MouseClicked

    private void tblPhanCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhanCongMouseClicked
        // TODO add your handling code here:
        clickTable();
    }//GEN-LAST:event_tblPhanCongMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblChamCong;
    private javax.swing.JTable tblPhanCong;
    private javax.swing.JTextField txtGioLam;
    private javax.swing.JTextField txtMaCĐ;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTenCĐ;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables

}
