/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author ADMIN
 */
public class pnTrangChu extends javax.swing.JPanel {

    /**
     * Creates new form pnTrangChu
     */
    public pnTrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setPreferredSize(new java.awt.Dimension(1200, 1015));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("TẬP ĐOÀN NƯỚC GIẢI KHÁT HEALTHY ");
        add(jLabel2);
        jLabel2.setBounds(320, 10, 750, 90);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("GIÁ TRỊ CỐT LÕI:");
        add(jLabel3);
        jLabel3.setBounds(20, 360, 220, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/number1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(890, 540, 180, 140);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/machiato.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(230, 540, 160, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/0do.jpg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(540, 540, 180, 140);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("3. Có trách nhiệm với cộng đồng và xã hội");
        add(jLabel6);
        jLabel6.setBounds(110, 480, 330, 21);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Ðóng góp cho sự phồn vinh của xã hội và là niềm tự hào của người Việt Nam bằng cách xây dựng Tập đoàn có Thương hiệu Quốc gia lớn");
        add(jLabel7);
        jLabel7.setBounds(110, 280, 1060, 21);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("VỀ CHÚNG TÔI");
        add(jLabel8);
        jLabel8.setBounds(20, 110, 190, 29);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Là đơn vị tiên phong giới thiệu ra thị trường ngành hàng nước giải khát có lợi cho sức khỏe với các nhãn hiệu nổi tiếng được yêu thích như:");
        add(jLabel9);
        jLabel9.setBounds(110, 150, 1060, 21);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Nước tăng lực Number 1, Trà xanh Không Độ, Trà thanh nhiệt Dr Thanh, Trà sữa Macchiato Không Độ, v.v...");
        add(jLabel10);
        jLabel10.setBounds(110, 190, 1060, 21);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("NGUYỆN VỌNG:");
        add(jLabel11);
        jLabel11.setBounds(20, 240, 220, 29);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("mạnh tầm cỡ quốc tế");
        add(jLabel12);
        jLabel12.setBounds(110, 320, 180, 21);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("1. Thỏa mãn khách hàng");
        add(jLabel13);
        jLabel13.setBounds(110, 400, 220, 21);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("2. Chất lượng chuẩn quốc tế");
        add(jLabel14);
        jLabel14.setBounds(110, 440, 240, 21);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
